title: Stastic Website Editor
title_fr: Stastic Web Editeur
description: Stastic is the easiest way to manage a static website.
description_fr: Stastic est le moyen le plus simple de gérer un site web statique.
github_repo: ''
github_username: ''
social_link: ''
social_username: ''
theme_color: light
baseurl: /www.stastic.net
url: ''
remote_theme_layouts:
  - default
  - home
  - page
  - post
  - category-post
  - category_index
permalink: '/:slug'

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "post"
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      lang: "en"
  -
    scope:
      path: "" 
      type: "fr" 
    values:
      lang: "fr"
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"


collections:
  posts:
    permalink: /docs/:slug
    output: true
  fr:
    permalink: /docs/fr/:slug
    output: true


#    permalink: /:collection/:name
exclude: [vendor]

