remote_theme: broccolini/athena
title: <img src="/assets/2019-08-02-951726.png">
description: Stastic is the easiest way to manage a static website.
github_repo: ''
github_username: internet-de-france
social_link: 'https://twitter.com/lexoyo'
social_username: lexoyo
theme_color: light
baseurl: /
url: 'https://www.stastic.net'
