remote_theme: broccolini/athena
theme: broccolini/athena
title: Stastic Website Editor
description: Stastic is the easiest way to manage a static website.
github_repo: ''
github_username: ''
social_link: ''
social_username: ''
theme_color: light
baseurl: /
url: 'https://www.stastic.net'
remote_theme_layouts:
  - default
  - home
  - page
  - post
  - category-post
  - category_index
permalink: '/:slug'
collections:
  posts:
    permalink: /docs/:slug
    lang: en
  fr:
    permalink: /docs/fr/:slug
    lang: fr

#    permalink: /:collection/:name
exclude: [vendor]

