remote_theme: broccolini/athena
title: Stastic<br />Website Editor
description: Stastic is the easiest way to get started to manage a static website
github_repo: ''
github_username: internet-de-france
social_link: 'https://twitter.com/lexoyo'
social_username: lexoyo
theme_color: light
baseurl: /
url: 'https://doc.stastic.net'
